version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.NPM_GH_TOKEN }}
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_TOKEN }}

updates:
## public (npmjs) registry only
  - package-ecosystem: "npm"
    directory: "/npm"
    registries:
      - npm-npmjs
    schedule:
      interval: "daily"
    labels:
      - manager:npm
      - registry:npmjs
  - package-ecosystem: "npm"
    directory: "/pnpm"
    registries:
      - npm-npmjs
    schedule:
      interval: "daily"
    labels:
      - manager:pnpm
      - registry:npmjs

## use github registry only
  - package-ecosystem: "npm"
    target-branch: "gh"
    directory: "/npm"
    registries:
      - npm-github
    schedule:
      interval: "daily"
    labels:
      - manager:npmjs
      - registry:github
  - package-ecosystem: "npm"
    target-branch: "gh"
    directory: "/pnpm"
    registries:
      - npm-github
    schedule:
      interval: "daily"
    labels:
      - manager:pnpm
      - registry:github


## use both private and public registries
  - package-ecosystem: "npm"
    target-branch: "mixed"
    directory: "/npm"
    registries:
      - npm-github
      - npm-npmjs
    schedule:
      interval: "daily"
    labels:
      - manager:npm
      - registry:npmjs
      - registry:github
  - package-ecosystem: "npm"
    target-branch: "mixed"
    directory: "/pnpm"
    registries:
      - npm-github
      - npm-npmjs
    schedule:
      interval: "daily"
    labels:
      - manager:pnpm
      - registry:npmjs
      - registry:github
  - package-ecosystem: "npm"
    target-branch: "all"
    directory: "/pnpm"
    registries: "*"
    schedule:
      interval: "daily"
    labels:
      - manager:pnpm
      - registry:npmjs
      - registry:github
